### ISSUE TITLE
Create Jupyter Notebook to process stoplist spreadsheets

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#105]

**Comment by matikin9** [comment]
Sample file with new columns we can use to parse the data.
[Copy of Line 260 Revised 10-12-21.xlsx](https://github.com/LACMTA/mybus/files/7566781/Copy.of.Line.260.Revised.10-12-21.xlsx)

**Comment by matikin9** [comment]
Waiting on access to the Dropbox folder with the stop list spreadsheets.

**Comment by albertkun** [comment]
Folder is here!
https://www.dropbox.com/home/December%202021%20Service%20Change?oref=e

**Comment by matikin9** [comment]
Current Google Sheet for stop changes:
https://docs.google.com/spreadsheets/d/1OR-Ii2zLDtVFDqES2WGoTF10SaP8qwkoe6YUIIQQ8VU/edit?usp=sharing

Published as a CSV:
https://docs.google.com/spreadsheets/d/e/2PACX-1vRg9oVntzWoLImtA3AFGTQYZoTa7JPMYG1TqjV__zIxpvaBhHG_ZWPyg_jaKt7TSVke2ZH3nEmGdzi3/pub?gid=1103678554&single=true&output=csv

**Comment by matikin9** [comment]
We did not end up automating the intake of the spreadsheets, we continued to manually copy/paste the contents into a Google Sheet and then used the existing Jupyter Notebook to process that data.
