### ISSUE TITLE
Take down dropdowns from page

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#107]
@EbbyEbby to provide copy from Antonio.

Target date is Nov 1 to replace home page with new copy and remove the dropdowns.

**Comment by EbbyEbby** [comment]
HI team I got copy approved from Ops and okay'd that we are changing the site on Nov 1st. Please use the following: Metro made changes to bus service on Sunday, September 12, 2021. The next round of updates are scheduled for Sunday, December 19, 2021. You can view our latest schedules here  or you can sign up to receive updates below. 
(Email sign-up button) @matikin9 @albertkun

**Comment by albertkun** [comment]
Thank you @EbbyEbby!!!

**Comment by albertkun** [comment]
@EbbyEbby email sign up now live on the [website](https://mybus.metro.net/)! thoughts?



![image](https://user-images.githubusercontent.com/8574425/139749197-bfc91d58-5f0b-4203-9f77-7664941f41af.png)
