### ISSUE TITLE
Create all changes data and page

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#108]
Need from @EbbyEbby :
- [x] copy edited takeone
- [x] translated takeone

**Comment by EbbyEbby** [comment]
[22-0509_NextGen_December_Service_Change_TK1_jp6.pdf](https://github.com/LACMTA/mybus/files/7479187/22-0509_NextGen_December_Service_Change_TK1_jp6.pdf)
Comp #6 attached, I don't forsee any major changes. English version was approved. @matikin9 @albertkun

**Comment by matikin9** [comment]
@EbbyEbby thanks for the file! i just realized though that this is the PDF and for the data work we'll need a Word/Excel file.  Can you send over the version being used for translations?  It's fine if it only has the English version of the copy in it, we just need some thing the code can use.

**Comment by matikin9** [comment]
@albertkun - new Google Sheet (but with September's data) is here: https://docs.google.com/spreadsheets/d/1qVdlckKCaBF7-B7LBpxwRnmGQBA2gULQLlPkboEfn6Y/edit?usp=sharing

**Comment by albertkun** [comment]
@matikin9  I do need access to the sheet:

![image](https://user-images.githubusercontent.com/8574425/141224341-ca6ab644-c937-49de-a0cb-b5413b17f4f8.png)

**Comment by albertkun** [comment]
Got it! Thanks! Will work on 11/11!

**Comment by EbbyEbby** [comment]
[22-0509 take one Trans-SPN only_EC edited 11.3.21.docx](https://github.com/LACMTA/mybus/files/7540613/22-0509.take.one.Trans-SPN.only_EC.edited.11.3.21.docx)
@matikin9  here you go.

**Comment by EbbyEbby** [comment]
@matikin9  also all other languages are here too.
[22-0836 take one Translations 8 Lang_(6 remaining languages).docx](https://github.com/LACMTA/mybus/files/7540622/22-0836.take.one.Translations.8.Lang_.6.remaining.languages.docx)

**Comment by matikin9** [comment]
@EbbyEbby We noticed that the wording in the Takeone and translation is a little ambiguous.  The Takeone brochure says "The following lines will have extra trips added in December." and the translations doc says "The following lines will have extra trips in December."  I assume this means starting in December (and going forward) but it could be taken to mean these extra trips will only be added for December.

**Comment by matikin9** [comment]
Added the above copy issue as well as some other issues that need to be addressed to this new issue: #121
