### ISSUE TITLE
Post-Nov 15 update fixes

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#121]
Issues that still need to be addressed:

- The wording in the Takeone and translation is a little ambiguous. The Takeone brochure says "The following lines will have extra trips added in December." and the translations doc says "The following lines will have extra trips in December." I assume this means starting in December (and going forward) but it could be taken to mean these extra trips will only be added for December. (@EbbyEbby - thoughts?)
- [x] #128
![image](https://user-images.githubusercontent.com/1873072/141877161-83c36086-de6b-4a42-ba6d-8c22241ed647.png)
- [x] Some translations are parsing off of the month number: (@matikin9 )
![image](https://user-images.githubusercontent.com/1873072/141877210-17cbc4c4-3507-47de-8e87-1650c1280762.png)
- [x] #129
- [x] #130

**Comment by EbbyEbby** [comment]
@matikin9  lets to rail designations as their full name- can you manually change those? As for copy you noted, should we say starting in Dec instead?

**Comment by EbbyEbby** [comment]
@matikin9 here are the copy edits that need to be reflected on take one. Only look at highlighted section the rest remains the same. Basically Line 200 has its own section now and there was a small deletion on Line 53. Let me know if there are any Q's. 
[22-0836 take one Translations Copy edits needed 11_15 (1)[46]_FINAL .docx](https://github.com/LACMTA/mybus/files/7558327/22-0836.take.one.Translations.Copy.edits.needed.11_15.1.46._FINAL.docx)
s!

**Comment by EbbyEbby** [comment]
@matikin9 @albertkun here are the new take one PDFS for all other languages... I am working on editing the Eng/Spn.
[F-22-0836_NextGen_December_Service_Change_TK1_jp-RUS.pdf](https://github.com/LACMTA/mybus/files/7573835/F-22-0836_NextGen_December_Service_Change_TK1_jp-RUS.pdf)
[D-22-0836_NextGen_December_Service_Change_TK1_jp-JAP.pdf](https://github.com/LACMTA/mybus/files/7573837/D-22-0836_NextGen_December_Service_Change_TK1_jp-JAP.pdf)
[C-22-0836_NextGen_December_Service_Change_TK1_jp-KOR.pdf](https://github.com/LACMTA/mybus/files/7573838/C-22-0836_NextGen_December_Service_Change_TK1_jp-KOR.pdf)
[B-22-0836_NextGen_December_Service_Change_TK1_jp-VIET.pdf](https://github.com/LACMTA/mybus/files/7573839/B-22-0836_NextGen_December_Service_Change_TK1_jp-VIET.pdf)
[A-22-0836_NextGen_December_Service_Change_TK1_jp-CHN.pdf](https://github.com/LACMTA/mybus/files/7573840/A-22-0836_NextGen_December_Service_Change_TK1_jp-CHN.pdf)

[E-22-0836_NextGen_December_Service_Change_TK1_jp-ARM.pdf](https://github.com/LACMTA/mybus/files/7573836/E-22-0836_NextGen_December_Service_Change_TK1_jp-ARM.pdf)

**Comment by matikin9** [comment]
@EbbyEbby - I created new issues to track these additions:

- #128 - show rail line names
- #129 - update copy for lines 200 and 53 (I see deletions for line 33, not 53?)
- #130 - upload new translated Take Ones

**Comment by EbbyEbby** [comment]
@matikin9 @albertkun so I swear last time we update the PDF's. Here are the new files- these just match the copy change we made in the last round. Let me know if you have any questions. 

[C-22-0836_NextGen_December_Service_Change_TK1_jp-KOR2.pdf](https://github.com/LACMTA/mybus/files/7620809/C-22-0836_NextGen_December_Service_Change_TK1_jp-KOR2.pdf)
- 
[D-22-0836_NextGen_December_Service_Change_TK1_jp-JAP2.pdf](https://github.com/LACMTA/mybus/files/7620810/D-22-0836_NextGen_December_Service_Change_TK1_jp-JAP2.pdf)
th
[E-22-0836_NextGen_December_Service_Change_TK1_jp-ARM2.pdf](https://github.com/LACMTA/mybus/files/7620811/E-22-0836_NextGen_December_Service_Change_TK1_jp-ARM2.pdf)
[F-22-0836_NextGen_December_Service_Change_TK1_jp-RUS2.pdf](https://github.com/LACMTA/mybus/files/7620812/F-22-0836_NextGen_December_Service_Change_TK1_jp-RUS2.pdf)
[22-0920_REV-NextGen_December_Service_Change_TK1_jp-web-ENG (1).pdf](https://github.com/LACMTA/mybus/files/7620804/22-0920_REV-NextGen_December_Service_Change_TK1_jp-web-ENG.1.pdf)
[22-0920_REV-NextGen_December_Service_Change_TK1_jp-web-SPN.pdf](https://github.com/LACMTA/mybus/files/7620806/22-0920_REV-NextGen_December_Service_Change_TK1_jp-web-SPN.pdf)
[A-22-0836_NextGen_December_Service_Change_TK1_jp-CHN2.pdf](https://github.com/LACMTA/mybus/files/7620807/A-22-0836_NextGen_December_Service_Change_TK1_jp-CHN2.pdf)
[B-22-0836_NextGen_December_Service_Change_TK1_jp-VIET2.pdf](https://github.com/LACMTA/mybus/files/7620808/B-22-0836_NextGen_December_Service_Change_TK1_jp-VIET2.pdf)
.
