### ISSUE TITLE
Japanese Take-all date incorrect

### ISSUE THREAD

**Issue by albertkun** [LACMTA/mybus#144]
The take-all in Japanese language has an incorrect date:
![image](https://user-images.githubusercontent.com/8574425/144133918-790b5a4c-e72e-4eb1-a677-c01833239ec2.png)

**Comment by matikin9** [comment]
For now, we've uploaded a version that Albert manually updated.

**Comment by EbbyEbby** [comment]
Here is updated version @albertku
[D-22-0836_NextGen_December_Service_Change_TK1_jp-JAP3.pdf](https://github.com/LACMTA/mybus/files/7639021/D-22-0836_NextGen_December_Service_Change_TK1_jp-JAP3.pdf)
n

**Comment by matikin9** [comment]
oh no @EbbyEbby! You tagged the wrong @albertkun !

**Comment by albertkun** [comment]
![image](https://user-images.githubusercontent.com/8574425/144680274-3818c5ec-4341-444b-976a-73c12ad9d825.png)
@EbbyEbby any chance we can put the `か` on the same line as `ら` without it it reads like 
`:fr
om`
