### ISSUE TITLE
Update Line Details pages to show maps

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#156]
@EbbyEbby to set up a meeting with Monica to see if she wants to provide input on a re-design.

**Comment by matikin9** [comment]
Get redesigned page in Dev site by end of Monday.  Show planners & customer care at Tuesday, Dec 21 meeting.

**Comment by matikin9** [comment]
Figma design: https://www.figma.com/file/pIupVMZ7PYOLMi9zygNGIY/MyBus?node-id=1801%3A3800

**Comment by albertkun** [comment]
The files:

https://www.dropbox.com/sh/qei5if43joxenn0/AAAC9tlBmhibJPmEy0lYotWUa/Route%20Change?dl=0&subfolder_nav_tracking=1

**Comment by matikin9** [comment]
Outstanding UI questions:

* have map image fully fill map window?
* have map window show only the extent of the map image so blank areas don't show up
* what zoom level to set limit to?
* what to set default map height to? maybe pull from figma
