### ISSUE TITLE
Add System Map to MyBus Tool 

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#158]
Hi team- can you link the system map today onto the mybus tool, we discussed somewhere in the all summary page- here's the link from the maps page https://www.dropbox.com/s/fy4auwjppt1rugp/22-0986_blt_system_map_47x47.5_DCR.pdf?dl=0 @matikin9 @albertkun

**Comment by albertkun** [comment]
Thanks @EbbyEbby ! I'll talk with @matikin9 tmr to see where in the page this best would fit!

**Comment by EbbyEbby** [comment]
@matikin9 there are 2 versions of system map, so not sure how we want to handle, the new one is already posted here https://www.metro.net/riding/guide/system-maps/

**Comment by matikin9** [comment]
Text:

> View the new <a href="">Bus and Rail System Detail Map</a> (effective Sunday 19, 2021).

Insert under the links to the Takeone PDFs, with as a new line with a space between the paragraphs:
![image](https://user-images.githubusercontent.com/1873072/146260291-1dfbd99f-0e19-4aa8-bac5-d818daf7ee7e.png)

**Comment by albertkun** [comment]
Closed with #165
