### ISSUE TITLE
All Changes page - add links to lines

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#162]
Request from Joe:

> On the all changes section would you be able to add a 179 link for the 79 and a 660 under the 260 section (as well as the 260 link).

Double-check that the Line Details pages also have these links.

**Comment by albertkun** [comment]
Made changes to the doc and re-ran the notebook to generate the links for 79 and 660, however I'm not sure which links you are talking about for the Line Details pages. Is it 79 and 179? 660 or 260? As it stands the 179 looks like this:
![image](https://user-images.githubusercontent.com/8574425/145915000-f403f454-c5c8-4210-8fcf-a034567e76fa.png)

Pitching back to you for you to provide more details @matikin9 !
