### ISSUE TITLE
Line 222 RITC

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#45]
For Line 222, no need to say RITC stop is being relocated. What is going away is only the Layover at the RITC which is already covered by the text, and won’t affect customers. The stop inside the Burbank Airport RITC actually is staying the same.

**Comment by albertkun** [comment]
Removed in the Google Spreadsheet:
![image](https://user-images.githubusercontent.com/8574425/131755533-0be441af-ff74-4a28-a7bd-9876e9e139a9.png)
