### ISSUE TITLE
Line 550 stops added 

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#47]
550 all stops in Blue need to be added. These have been added because service was restored. 
[Copy of Copy of list_550 Effective 06-23-13 Revised 08-13-20.xls](https://github.com/LACMTA/mybus/files/7094593/Copy.of.Copy.of.list_550.Effective.06-23-13.Revised.08-13-20.xls)

**Comment by EbbyEbby** [comment]
@matikin9  yes anything with service restored, we can handle like #40

**Comment by matikin9** [comment]
@EbbyEbby Yikes, this is a lot of stops:

![image](https://user-images.githubusercontent.com/1873072/131761758-26559819-3415-4b24-85aa-b2e187194228.png)

**Comment by EbbyEbby** [comment]
@matikin9  should we say instead service has been restored at certain stops, see timetable for details- maybe then we don't list this huge list. thoughts?

**Comment by matikin9** [comment]
I'm fine with that!  Although I'm looking at the timetable itself and... yikes!  I can't wait for us to have a better map representation of the routes.

**Comment by matikin9** [comment]
@EbbyEbby Here's a preview.  Does this look good?

![image](https://user-images.githubusercontent.com/1873072/131762259-7f7f0935-6b30-469f-94c5-06a2a8ea1646.png)
