### ISSUE TITLE
Line 242 & 243- link to metro micro

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#49]
On Lines  242 and 243, is it possible to offer a link to the New Metro Micro zone?

**Comment by matikin9** [comment]
@EbbyEbby is there a specific landing page URL you want to use?

**Comment by matikin9** [comment]
Add link to the above URL in the Google Sheet.  The notebook needs to be re-run so it gets pulled into the website.

We can change the URL if needed.

**Comment by EbbyEbby** [comment]
> @EbbyEbby is there a specific landing page URL you want to use? This one? https://micro.metro.net/zone-map-north-west-san-fernando-valley/

Yes, that's correct!

**Comment by matikin9** [comment]
@albertkun for the all changes page, the details reference a footnote at the bottom of the page.  It might be easier for now to just turn that URL in that line into a proper link:

![image](https://user-images.githubusercontent.com/1873072/131900768-74b4b36e-3622-4b91-989d-30c0ca0f114e.png)
