### ISSUE TITLE
Summary of stop list comments 

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#50]
team- one planner took the time to add in comments to spreadsheet. Might be easier to review all at once. 
[EDITED-stop_changes_with_names - IM.xlsx](https://github.com/LACMTA/mybus/files/7094683/EDITED-stop_changes_with_names.-.IM.xlsx)

**Comment by matikin9** [comment]
:D any details on what/where their comments are?

**Comment by EbbyEbby** [comment]
Click the comments icon on right side and they should pop up, each section you can also see it tagged.

**Comment by albertkun** [comment]
@matikin9 @EbbyEbby  changes from the Excel Spreadsheet were made onto the Google Doc!

**Comment by albertkun** [comment]
On-Hold: @matikin9 needs run in the Jupyter Notebook

**Comment by albertkun** [comment]
@EbbyEbby testing!
