### ISSUE TITLE
Insert map images for lines with route changes

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#52]
@EbbyEbby what do you think?

@albertkun and I were thinking we should include screenshots of the maps from the printed signs for the 222/622, 242/243, 4/704, 106, and the 18 (stop relocations).  Any others where routes are changing and riders would benefit from a map visual?

**Comment by albertkun** [comment]
@EbbyEbby can we include these images of the lines with route changes?

**Comment by EbbyEbby** [comment]
@matikin9 @albertkun  I am not opposed, but some of the maps may differ from one another, do you think that will be an issue? The planners don't always create the maps in the same format but we can look at these- do you need screen shots or what is best way for me to provide these to you?

**Comment by albertkun** [comment]
Addressed in #156
