### ISSUE TITLE
Add copy for "More Trips"

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#53]
We took this out when we switched to using just the Details column. I forgot that what we had done last time is turn the "More Trips" columns into copy in the "Schedule" column.  We just need to restore that part of the code in `bus.js` and add in the relevant copy to the Google Sheet.

**Comment by matikin9** [comment]
@EbbyEbby can we get Antonio to do add this in tomorrow?  We can discuss tomorrow.

**Comment by EbbyEbby** [comment]
@matikin9  yes, maybe I should invite him to the meeting tomorrow and we can give him further instructions... oh wait he's on vacation I think. Let me double check.
