### ISSUE TITLE
All changes copy edits (Line 2, 33, 602) 

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#61]
@matikin9 
Add Eng copy: The following stops are cancelled:
Spanish: Las siguientes paradas están canceladas: 

Line 2- add 1 pair- sunset/mapleton
Line 33- 4 total (2 locations) 
Line 602- I stop pair

**Comment by matikin9** [comment]
@EbbyEbby the 4 also, right?

**Comment by matikin9** [comment]
do you have a translation for "westbound" and "eastbound"?

**Comment by matikin9** [comment]
westbound: hacia el oeste
eastbound: hacia el este
