### ISSUE TITLE
Add stops to dropdown for lines 110 and 550 where service is restored

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#62]
Service is being restored so we can make the case that riders that previously used these stops are familiar with them.

- [x] Add the restored stops to the dropdown list.
- [x] Add the stops with a new category of "service_restored" to the stop changes Google Sheet
- [x] Make sure they show up on the front end with the message "Service to this stop is restored"

**Comment by matikin9** [comment]
Line 110

| stop_id | stop_name | direction|
| --- | --- | --- |
|65300037 | WATERS EDGE / JEFFERSON | EB & WB |
|176153 | JEFFERSON / CONCERT PARK DRIVE |EB|
|2701 | JEFFERSON / BEETHOVEN|EB|
|11194 | JEFFERSON / MC CONNELL|EB|
|2702| JEFFERSON / MC CONNELL|WB|
|2703| JEFFERSON / WESTLAWN|EB|
|11197| JEFFERSON / WESTLAWN|WB|
|2704 | JEFFERSON / CAMPUS CENTER DRIVE|EB|
|140878 | JEFFERSON / CENTINELA| EB|
|20501| JEFFERSON / CENTINELA| WB|
|2705| JEFFERSON / MESMER| EB|
|11195| JEFFERSON / MESMER| WB|
|2706| JEFFERSON / SLAUSON|EB|
|16943| JEFFERSON / SLAUSON|WB|
|14660|SLAUSON / SEPULVEDA|WB|
|12124|JEFFERSON / INGLEWOOD|WB|
|8683|JEFFERSON / ALLA RD|WB|

Line 550

| stop_id | stop_name | direction|
| --- | --- | --- |
|30005|HARBOR GATEWAY TC / BAY 05|NB|
|2321|HARBOR TRANSIT WAY / ROSECRANS|NB|
|10855|HARBOR TRANSIT WAY / I105 GREEN LINE STA|NB|
|2320|HARBOR TRANSIT WAY / MANCHESTER|NB|
|2322|HARBOR TRANSIT WAY / SLAUSON|NB|
|7262|39TH ST / FIGUEROA|NB|
|1886|EXPOSITION / FIGUEROA|NB|
|10378|EXPOSITION / TROUSDALE WALK|NB|
|10390|EXPOSITION / WATT WAY|NB|
|5635|VERMONT / EXPOSITION|NB|
|5656|VERMONT / 36th PL|NB|
|7766|JEFFERSON / VERMONT|NB|
|7752|JEFFERSON / MC CLINTOCK|NB|
|2457|MC CLINTOCK / JEFFERSON|NB|
|2457|MC CLINTOCK / JEFFERSON|SB|
|2458|JEFFERSON / MC CLINTOCK|SB|
|140951|VERMONT / JEFFERSON|SB|
|14039|VERMONT / 36th PL|SB|
|1841|EXPOSITION / VERMONT|SB|
|12002|EXPOSITION / WATT WAY|SB|
|1830|EXPOSITION / UNIVERSITY WALK|SB|
|10437|EXPOSITION / FIGUEROA|SB|
|13424|FIGUEROA / STATE|SB|
|15616|39TH ST / FIGUEROA|SB|
|10994|HARBOR TRANSIT WAY / SLAUSON|SB|
|10853|HARBOR TRANSIT WAY / MANCHESTER|SB|
|2324|HARBOR TRANSIT WAY / I105 GREEN LINE STA|SB|
|10846|HARBOR TRANSIT WAY / ROSECRANS|SB|

**Comment by EbbyEbby** [comment]
Here are the spreadsheets that Scott had sent me- only adding blue 
[Copy of Copy of list_550 Effective 06-23-13 Revised 08-13-20 (1).xls](https://github.com/LACMTA/mybus/files/7146690/Copy.of.Copy.of.list_550.Effective.06-23-13.Revised.08-13-20.1.xls)
[Copy of Copy of list_110 Effective 6-27-21 add Playa Vista (1).xls](https://github.com/LACMTA/mybus/files/7146691/Copy.of.Copy.of.list_110.Effective.6-27-21.add.Playa.Vista.1.xls)

**Comment by matikin9** [comment]
@EbbyEbby ok, good, these are what I used!
