### ISSUE TITLE
Day-Of Shakeup Updates

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#86]
Route description updates for Schedules page and MyBus site, from Joe Forgiarini:

- [x] Line 30 - "West Hollywood" should be replaced by "Pico Rimpau Transit Center".
- [x] Line 106 - include "LA Union Station", "Little Tokyo" in the middle
- [x] Line 152 - replace "Topanga Canyon" with "West Hills Medical Center"
- [x] Line 222 - remove reference to 656, add "Tuxford / Lankershim" at the start
- [x] Line 224 - add "Includes Overnight Owl service to Hollywood"
- [x] 242/243 - change "Porter Ranch" to "Devonshire St"

- [x] Upload new schedules to metro.net
- [x] Re-run MyBus notebook for the new descriptions

-----
## Issues

- [x] How to replace schedule PDFs - use Line Overrides file field.

- [x] Schedule button doesn't work for these lines:

* ~10/48 - Separate schedule PDFs provided.~
* ~14/37 - Separate schedule PDFs provided.  Description set to "Beverly Center - Downtown LA - Washington/Fairfax via Beverly-Adams" but the schedule PDF lists Cedars Sinai instead of Beverly Center.~
* ~35/38 - Separate schedule PDFs provided. Description set to "Downtown LA - Washington/Fairfax via Washington Bl & Jefferson Bl"~
* ~78/79 - Description set to "Downtown LA - Washington/Fairfax via Washington Bl & Jefferson Bl"~
* ~211/215~
* ~224/690 - Separate schedule PDFs provided.~
* ~235/236~
* ~242/243~
* ~487/489~
* ~854 (L Line Shuttle)~
* ~901 (G Line)~
* ~910/950 (J Line)~

- [ ] ~SOFI - SoFi Stadium Express not showing up correctly~ Created issue for this in metro-dot-net repo
- [ ] ~Dodger Stadium Express - not showing up at all~ Created issue for this in metro-dot-net repo

Lower priority:

- [ ] ~230, 232, 233 - out of order in the Schedules page.~ Created issue for this in metro-dot-net repo
- [ ] Schedules pages maps showing stop markers, up to a certain zoom level, but no connecting line.

**Comment by matikin9** [comment]
Schedule button doesn't work for these lines that have sister routes:

* 10/48 - Separate schedule PDFs provided.
* 14/37 - Separate schedule PDFs provided.  Description set to "Beverly Center - Downtown LA - Washington/Fairfax via Beverly-Adams" but the schedule PDF lists Cedars Sinai instead of Beverly Center.
* 35/38 - Separate schedule PDFs provided. Description set to "Downtown LA - Washington/Fairfax via Washington Bl & Jefferson Bl"
* 78/79 - Description set to "Downtown LA - Washington/Fairfax via Washington Bl & Jefferson Bl"
* 211/215
* 224/690
* 235/236
* 242/243
* 487/489

30 - WP Schedules page updated.  Line changes Google Sheet updated, but notebook needs to be re-run and published for MyBus.

90 - Stops not showing up on schedule page.

106 - Set description to "Monterey Park - Cal State LA - LA Union Station - Little Tokyo - Montebello via Garvey Av & 1st St"

230, 232, 233 - out of order in the Schedules page.

SOFI - not showing up correctly

**Comment by albertkun** [comment]
Do we need to address any of these soon? @matikin9

**Comment by matikin9** [comment]
Oops @albertkun, I just saw your comment!  I'll defer to @Chaparroa on these remaining issues as they are all on metro.net.
